PAD_IDX = 0
UNK_IDX = 1
SOS_IDX = 2
EOS_IDX = 3 


SPECIAL_SYMBOLS = ['<pad>', '<unk>', '<sos>', '<eos>']

PAD_STRING__VALUE = SPECIAL_SYMBOLS[0]
UNK_STRING_VALUE = SPECIAL_SYMBOLS[1]
SOS_STRING_VALUE = SPECIAL_SYMBOLS[2]
EOS_STRING_VALUE = SPECIAL_SYMBOLS[3]

